apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.bucket.name }}
  labels:
    {{- include "rgw-bucket-helper.labels" . | nindent 4 }}
data:
  BUCKET_HOST: {{ .Values.s3.host }}
  BUCKET_PORT: '443'
  BUCKET_NAME: {{ include "rgw-bucket-helper.bucketFullname" . }}
