kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "rgw-user-setup-job.fullname" . }}-exec-{{ .Release.Namespace }}
  namespace: openshift-storage
  annotations:
    "helm.sh/hook-weight": "-5"
  labels:
    {{- include "rgw-user-setup-job.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "rgw-user-setup-job.serviceAccountName" . }}
    namespace: {{ .Release.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "rgw-user-setup-job.fullname" . }}-exec-{{ .Release.Namespace }}
