apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "rgw-user-setup-job.fullname" . }}-cleanup-{{ .Release.Revision }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
    {{- include "rgw-user-setup-job.labels" . | nindent 4 }}
spec:
  selector: {}
  template:
    metadata:
      name: {{ include "rgw-user-setup-job.fullname" . }}-cleanup
    spec:
      containers:
        - name: s3-secret-removal
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
            - name: SECRET_NAME
              value: {{ .Values.secret.name }}
          command:
            - /bin/bash
            - -c
            - |
              oc delete secret ${SECRET_NAME}

      restartPolicy: Never
      serviceAccount: {{ include "rgw-user-setup-job.serviceAccountName" . }}
      serviceAccountName: {{ include "rgw-user-setup-job.serviceAccountName" . }}
