apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "rgw-user-setup-job.fullname" . }}-secrets
  labels:
    {{- include "rgw-user-setup-job.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook-weight": "-5"
rules:
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - get
      - list
      - patch
      - label
      - update
      - create
      - delete
