{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rgw-user-setup-job.serviceAccountName" . }}
  labels:
    {{- include "rgw-user-setup-job.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook-weight": "-5"
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
