kind: Secret
apiVersion: v1
metadata:
metadata:
  name: {{ include "postgresql.fullname" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
stringData:
  database-name: {{ .Values.database.name }}
  database-password: {{ .Values.database.password }}
  database-user: {{ .Values.database.user }}
type: Opaque
