odhCommon:
  # -- Enable install of ODH Common resources
  enabled: true

seldon: 
  operator:
    # -- Enable install of Seldon Operator
    enabled: false

superset: 
  # -- Enable install of Apache Superset instance
  enabled: false

kafka:
  operator:
    # -- Enable install of the Strimzi Kafka Operator
    enabled: false
  instance:
    # -- Enable install of a Kafka instance
    enabled: false

grafana: 
  operator:
    # -- Enable install of the Grafana Operator
    enabled: false
  instance:
    # -- Enable install of a Grafana instance
    enabled: false

prometheus:
  operator:
    # -- Enable install of the Prometheus Operator
    enabled: false
    # -- Enable install of a Prometheus instance
  instance:
    enabled: false

spark: 
  # -- Enable install of the Spark Operator
  enabled: false

jupyterHub: 
  # -- Enable the install of a JupyterHub instance
  enabled: true
  additionalNotebooks:
    # -- Enable the install of additional Jupyter Notebook images
    enabled: true
  singleUserProfile: 
    # -- Enable the configuration of a singleUserProfile for JupyterHub
    enabled: false
    # profile:
    #   profiles:
    #   - name: preload repos
    #     env:
    #       - name: JUPYTER_PRELOAD_REPOS
    #         value: https://github.com/guimou/xraylab_notebooks.git
    #   - name: globals
    #     resources:
    #       requests:
    #         memory: 500m
    #         cpu: 500m
    #       limits:
    #         memory: 1Gi
    #         cpu: 1

airflow: 
  operator:
    # -- Enable install of the Airflow Operator
    enabled: false
  instance:
    # -- Enable install of the Airflow instance
    enabled: false
    
argoWorkflows:
  operator:
    # -- Enable install of the Argo Workflows Operator
    enabled: false
  instance:
    # -- Enable install of the Argo Workflows instance
    enabled: false

modelMesh:
  # -- Enable install of the Model Mesh instnace
  enabled: false

odhDashboard: 
  # -- Enable install of the ODH Dashboard instance
  enabled: true

repos:
  # -- KubeFlow manifest URL
  kfManifestsUrl: 'https://github.com/opendatahub-io/manifests/tarball/v1.4.0-rc.2-openshift'
  # -- ODH Manifests URL base
  manifestsUrl: 'https://github.com/opendatahub-io/odh-manifests/tarball/'
  # Overrides the manifestsVersion whose default is the chart appVersion.
  # -- Used to overwrite teh manifestsURL version from the chart appVersion
  # @default -- Chart appVersion
  manifestsVersion: ""
