apiVersion: v2
name: mlflow-server
description: A Helm chart for deploying mlflow on OpenShift
type: application

version: 0.1.0
appVersion: "1.25"

icon: https://avatars.githubusercontent.com/u/39938107

dependencies:
  - name: "postgrescluster"
    version: "0.2.2"
    repository: "https://strangiato.github.io/helm-charts/"
    condition: crunchyPostgres.enabled
