name: docs-build
on:
  push:
    branches:
      - main

jobs:
  docs-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build helm-docs
        uses: docker://docker.io/jnorwood/helm-docs:latest
        run: helm-docs
      - uses: EndBug/add-and-commit@v9 
        with:
          message: 'Automatic build of docs from GitHub Action'
