name: docs-build
on:
  push:
    branches:
      - main

jobs:
  docs-build:
    runs-on: ubuntu-latest
    container:
      image: docker.io/jnorwood/helm-docs:latest
    steps:
      - uses: actions/checkout@v2
      - name: Build helm-docs
        run: helm-docs
      - uses: stefanzweifel/git-auto-commit-action@v4
