name: release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: docker.io/jnorwood/helm-docs:latest
    steps:
      - uses: actions/checkout@v2
      - name: Build helm-docs
        run: helm-docs charts/hello-openshift
      - uses: EndBug/add-and-commit@v9 
        with:
          message: 'Automatic build of docs from GitHub Action'
